name: Deploy to Production

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: echo "${{ secrets.ENV_PRODUCTION}}" > .local.env
      - name: Build docker image
        run: docker build --platform linux/amd64 -t ductran201/suitweb:v0 .
      - name: Login to dockerhub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push docker image
        run: docker push ductran201/suitweb:v0
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Excecuting remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull ductran201/suitweb:v0
            docker stop prod-suitweb
            docker rm prod-suitweb
            docker run -dp 5173:5173 --name prod-suitweb ductran201/suitweb:v0
